const assetConstants = {
  news: "/assets/png/news.jpeg",
  news1: "/assets/png/news1.png",
  news2: "/assets/png/news2.png",
  news3: "/assets/png/news3.png",
  aboutUs: "/assets/png/about-us.png",
  banner: "/assets/png/banner.png",
  banner2: "/assets/png/banner2.jpeg",
  banner3: "/assets/png/banner3.webp",
  bannerChoose: "/assets/png/banner-choose.jpeg",
  bannerCompany: "/assets/png/banner-company.png",
  beOur: "/assets/png/be-our.jpeg",
  career: "/assets/png/career.png",
  logo: "/assets/png/logo.png",
  miniLogo: "/assets/png/mini-logo.png",
  footerLogo: "/assets/png/logo-footer.png",
  review: "/assets/png/review.png",
  review1: "/assets/png/review1.png",
  review2: "/assets/png/review2.png",
  review3: "/assets/png/review3.png",
  review4: "/assets/png/review4.png",
  review5: "/assets/png/review5.png",
  services: "/assets/png/service.png",
  services1: "/assets/png/service1.png",
  services2: "/assets/png/service2.png",
  services3: "/assets/png/service3.png",
  webFlow: "/assets/png/webflow-black.png",
  relume: "/assets/png/relume-black.png",
  forEmployeeBanner: "/assets/png/for-employee.png",
};


export default assetConstants;